// <auto-generated />
using ApacheLogs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ApacheLogs.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20171221074907_FixNameRequestTable")]
    partial class FixNameRequestTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApacheLogs.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileName");

                    b.Property<string>("PageName");

                    b.Property<string>("Path");

                    b.Property<int>("SizeFile");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ApacheLogs.Models.IpAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyName");

                    b.Property<string>("IP")
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.ToTable("IPs");
                });

            modelBuilder.Entity("ApacheLogs.Models.LogFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("logFiles");
                });

            modelBuilder.Entity("ApacheLogs.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("FileId");

                    b.Property<int>("IPAddressId");

                    b.Property<int>("LogFileId");

                    b.Property<int>("ResultOfRequest");

                    b.Property<string>("TypeOfRequest");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("IPAddressId")
                        .IsUnique();

                    b.HasIndex("LogFileId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ApacheLogs.Models.Request", b =>
                {
                    b.HasOne("ApacheLogs.Models.File", "File")
                        .WithOne("Request")
                        .HasForeignKey("ApacheLogs.Models.Request", "FileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ApacheLogs.Models.IpAddress", "IP")
                        .WithOne("Request")
                        .HasForeignKey("ApacheLogs.Models.Request", "IPAddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ApacheLogs.Models.LogFile", "LogFile")
                        .WithMany("request")
                        .HasForeignKey("LogFileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
